name: Proteger Branch Main

on:
  pull_request:
    branches:
      - main

jobs:
  check-source-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checa se a branch é a develop
        run: |
          if [ "${{ github.head_ref }}" != "develop" ]; then
            echo "Error: You can only merge into main from the develop branch!"
            exit 1
          else
            echo "Branch de origem válida: develop"
          fi